// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFc2qq7Uudo8w3UvGDgl9Stn8qaHAdOeA',
    appId: '1:800333772675:android:3efb80e652628661e7a8b6',
    messagingSenderId: '800333772675',
    projectId: 'blue4-commongrounds',
    storageBucket: 'blue4-commongrounds.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD36MIS_ce4K_UXkZ1BKoG5tvctPLQmBlY',
    appId: '1:800333772675:web:b40fdf7fd641d056e7a8b6',
    messagingSenderId: '800333772675',
    projectId: 'blue4-commongrounds',
    authDomain: 'blue4-commongrounds.firebaseapp.com',
    storageBucket: 'blue4-commongrounds.firebasestorage.app',
    measurementId: 'G-VPDPK3N3YC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKPOpL6xYmhxukPvuB8sJsqxuWuC61uQg',
    appId: '1:800333772675:ios:8e4485ed15e40f2de7a8b6',
    messagingSenderId: '800333772675',
    projectId: 'blue4-commongrounds',
    storageBucket: 'blue4-commongrounds.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKPOpL6xYmhxukPvuB8sJsqxuWuC61uQg',
    appId: '1:800333772675:ios:d5bf1a795109ca70e7a8b6',
    messagingSenderId: '800333772675',
    projectId: 'blue4-commongrounds',
    storageBucket: 'blue4-commongrounds.firebasestorage.app',
    iosBundleId: 'com.sanjaykarunamoorthy.common',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD36MIS_ce4K_UXkZ1BKoG5tvctPLQmBlY',
    appId: '1:800333772675:web:945b3af86d5cb67ee7a8b6',
    messagingSenderId: '800333772675',
    projectId: 'blue4-commongrounds',
    authDomain: 'blue4-commongrounds.firebaseapp.com',
    storageBucket: 'blue4-commongrounds.firebasestorage.app',
    measurementId: 'G-DPDVVVGB5V',
  );
}
